### ISSUE TITLE
Some words like &#55357;&#56452;&#55357;&#56388;&#55357;&#56416; can't be parse

### ISSUE THREAD

**Issue by fantasylion** [jzhang2004/vtd-xml#12]
Hi 
 I have xml like this

```XML
<last-name>&#55357;&#56452;&#55357;&#56388;&#55357;&#56416;糖</last-name>
```
when I parse the xml will be error here

```java
com.ximpleware.extended.EntityExceptionHuge: Errors in entity reference: Invalid XML char.
	at com.ximpleware.extended.VTDGenHuge.entityIdentifier(VTDGenHuge.java:980)
	at com.ximpleware.extended.VTDGenHuge.getCharAfterSe(VTDGenHuge.java:1119)
	at com.ximpleware.extended.VTDGenHuge.parse(VTDGenHuge.java:1445)
	at com.ximpleware.extended.VTDGenHuge.parseFile(VTDGenHuge.java:1293)
	at com.baozun.sql.maker.MemberSqlFactory.main(MemberSqlFactory.java:364)
```
What can I do to fix it. some one can help me.

**Comment by jzhang2004** [comment]
Thanks for reporting I will need to look into it...

**Comment by jzhang2004** [comment]
I think that the character encoded in the entity reference &#55357 does not fall into the category of a valid xml character... that is the reason...your xml is not well formed.
