### ISSUE TITLE
Regression in XMLMemMapperBuffer

### ISSUE THREAD

**Issue by bdecarne** [jzhang2004/vtd-xml#8]
Hi there,

This code works as expected in 2.11 : 

```java
VTDGenHuge vgh = new VTDGenHuge();
if (vgh.parseFile("c:/xml/text1.xml",true , VTDGenHuge.MEM_MAPPED)) {
     VTDNavHuge vnh = vgh.getNav();
     vnh.toElement(VTDNavHuge.FC);
     long[] la = vnh.getElementFragment();
     vnh.getXML().writeToFileOutputStream(new FileOutputStream("c:/xml/text2.xml"), la[0], la[1]);
}
```

But since 2.12, it raise this error : 

```
java.nio.channels.ClosedChannelException
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
	at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:588)
	at com.ximpleware.extended.XMLMemMappedBuffer.writeToFileOutputStream(XMLMemMappedBuffer.java:104)
```

The line https://github.com/jzhang2004/vtd-xml/blob/master/ximple-dev/com/ximpleware/extended/VTDGenHuge.java#L927 close the FileChannel at the end of vgh.getNav();

Have a nice day !

**Comment by jzhang2004** [comment]
Thanks.. will look into it 
There are other bugs that have been reported and fixed... will go out
in 2.13.2 

----- Original Message -----
From: jzhang2004/vtd-xml 
To:"jzhang2004/vtd-xml" 
Cc:"Subscribed" 
Sent:Fri, 10 Feb 2017 17:39:08 -0800
Subject:[jzhang2004/vtd-xml] Regression in XMLMemMapperBuffer (#8)

	Hi there, 

	This code works as expected in 2.11 : VTDGenHuge vgh = new
VTDGenHuge(); if (vgh.parseFile("c:/xml/text1.xml [1]",true ,
VTDGenHuge.MEM_MAPPED)) { VTDNavHuge vnh = vgh.getNav();
vnh.toElement(VTDNavHuge.FC); long[] la = vnh.getElementFragment();
vnh.getXML().writeToFileOutputStream(new
FileOutputStream("c:/xml/text2.xml [2]"), la[0], la[1]); } 

	But since 2.12, it raise this error :
java.nio.channels.ClosedChannelException [3] at
sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110) [4] at
sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:588) [5] at
com.ximpleware.extended.XMLMemMappedBuffer.writeToFileOutputStream(XMLMemMappedBuffer.java:104)
[6]  

	The line
https://github.com/jzhang2004/vtd-xml/blob/master/ximple-dev/com/ximpleware/extended/VTDGenHuge.java#L927
[7] close the FileChannel at the end of vgh.getNav(); 

	Have a nice day ! 

	—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub [8], or mute the
thread [9].     

Links:
------
[1] http://text1.xml
[2] http://text2.xml
[3] http://java.nio.channels.ClosedChannelException
[4] http://sitemail.hostway.com/http:
[5] http://sitemail.hostway.com/http:
[6] http://sitemail.hostway.com/http:
[7]
https://github.com/jzhang2004/vtd-xml/blob/master/ximple-dev/com/ximpleware/extended/VTDGenHuge.java#L927
[8] https://github.com/jzhang2004/vtd-xml/issues/8
[9]
